name: Docker Image CI

on:
  push:
    branches: [ "main", "develop", "feature/PS-1_CodeChallenge" ]
  pull_request:
    branches: [ "main", "develop", "feature/PS-1_CodeChallenge" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag miguno/ProductApi:$(date +%s)
